new_columns = { "Classical music":"1_classical", 
                "Punk Rock music": "1_punk",
                "Folk music":"1_folk",
                "Country music":"1_country",
                "Pop music":"1_pop",
                "Ed Sheeran":"1_sheeran",
                "The Beatles":"1_beatles",
                "Billie Eilish":"1_eilish",
                "The Rolling Stones":"1_stones",
                "David Bowie":"1_bowie",
                "5 Seconds of Summer":"1_summer",
                "I mostly  listen to CDs":"2_cds",
                "I mostly use Spotify or another music streaming service":"2_stream",
                "I mostly listen to the radio":"2_radio",
                "I mostly use the internet":"2_internet",
                "It's a Wonderful Life":"3_wonderful",
                "Start Wars series":"3_starwars",
                "Harry Potter series":"3_harrypotter",
                "Love Actually":"3_loveactually",
                "Casablanca":"3_casablanca",
                "Toy Stories series":"3_toystory",
                "2001 Space Odyssey":"3_spaceodyssey",
                "Back to the Future":"3_backtofuture",
                "Apocalypse Now":"3_apocolypsenow",
                "None of the above films":"3_none",
                "Friends":"4_friends",
                "Only Fools and Horses":"4_onlyfools",
                "Doctor Who":"4_doctorwho",
                "Downtown Abbey":"4_downtonabbey",
                "Gavin and Stacey":"4_gavinandstacey",
                "Game of Thrones":"4_gameofthrones",
                "The Thick of It":"4_thethickofit",
                "The Inbetweeners":"4_inbetweeners",
                "The Next Step":"4_thenextstep",
                "None of the above tv shows":"4_none",
                "I only watch live TV":"5_onlylive",
                "I sometimes watch live TV (eg news or sports) and sometimes watch recorded programs":"5_somelivesomerecord",
                "I mostly watch recorded programs on my TV":"5_record",
                "I mostly watch TV series online (computer, tablet, iPad, phone, etc.)":"5_online",
                "I don't really watch TV programs":"5_none",
                "I don't use any social media app":"6_none",
                "Facebook":"6_facebook",
                "Twitter":"6_twitter",
                "WhatsApp":"6_whatsapp",
                "Instagram":"6_instagram",
                "Pinterest":"6_pintrest",
                "Snapchat":"6_snapchat",
                "Skype":"6_skype",
                "LinkedIn":"6_linkedin",
                "Myspace":"6_myspace",
                "I don't own a smart phone":"7_none",
                "Less than 2 hours":"7_l2",
                "Between 2 and 5 hours":"7_b2a5",
                "Between 5 and 10 hours":"7_b5a10",
                "Between 10 and 20 hours":"7_b10a20",
                "Between 20 and 30 hours":"7_b20a30",
                "More than 30 hours":"7_m30",
                "I mostly use cash":"8_cash",
                "I mostly use cards":"8_card",
                "I mostly use Apple Pay or Android Pay or Samsung Pay":"8_applepay",
                "#######":"9_over18"}

final_columns = {"Classical":"1_classical",
                 "Rock":"1_rock",
                 "Country": "1_country",
                 "Pop": "1_pop",
                 "Indie": "1_indie",
                 "Electronic": "1_electronic",
                 "Hip-hop/Rap":"1_hiphoprap",
                 "None of the above genres": "1_none",
                 "I mostly  listen to CDs":"2_cds",
                "I mostly use Spotify or another music streaming service":"2_stream",
                "I mostly listen to the radio":"2_radio",
                "I mostly use YouTube or other websites":"2_youtube",
                "It's a Wonderful Life":"3_wonderful",
                "Star Wars series":"3_starwars",
                "Harry Potter series":"3_harrypotter",
                "Love Actually":"3_loveactually",
                "Casablanca":"3_casablanca",
                "Toy Story series":"3_toystory",
                "2001 Space Odyssey":"3_spaceodyssey",
                "Back to the Future":"3_backtofuture",
                "Apocalypse Now":"3_apocolypsenow",
                "None of the above films":"3_none",
                "Friends":"4_friends",
                "Only Fools and Horses":"4_onlyfools",
                "Doctor Who":"4_doctorwho",
                "Downtown Abbey":"4_downtonabbey",
                "Gavin and Stacey":"4_gavinandstacey",
                "Game of Thrones":"4_gameofthrones",
                "The Thick of It":"4_thethickofit",
                "The Inbetweeners":"4_inbetweeners",
                "The Next Step":"4_thenextstep",
                "None of the above tv shows":"4_none",
                "I mostly watch live TV (eg news or sports)":"5_live",
                "I mostly watch recorded programs on my TV":"5_record",
                "I mostly watch TV series online (computer, tablet, iPad, phone, etc.)":"5_online",
                "I don't really watch TV programs":"5_none",
                 "I don't use any social media app":"6_none",
                "Facebook":"6_facebook",
                "Twitter":"6_twitter",
                "WhatsApp":"6_whatsapp",
                "Instagram":"6_instagram",
                "Pinterest":"6_pintrest",
                "Snapchat":"6_snapchat",
                "LinkedIn":"6_linkedin",
                "I don't own a smart phone":"7_none",
                "Less than 5 hours":"7_l5",
                "Between 5 and 10 hours":"7_b5a10",
                "Between 10 and 20 hours":"7_b10a20",
                "Between 20 and 30 hours":"7_b20a30",
                "More than 30 hours":"7_m30",
                "I mostly use cash":"8_cash",
                "I mostly use cards":"8_card",
                "I mostly use Apple Pay or Android Pay or Samsung Pay":"8_applepay",
                "#######":"9_over18"}
                 

columns_encoding = {"Classical":0,
                 "Rock":1,
                 "Country": 2,
                 "Pop": 3,
                 "Indie": 4,
                 "Electronic": 5,
                 "Hip-hop/Rap":6,
                 "None of the above genres": 7,
                 "I mostly  listen to CDs":0,
                "I mostly use Spotify or another music streaming service":1,
                "I mostly listen to the radio":2,
                "I mostly use YouTube or other websites":3,
                "It's a Wonderful Life":0,
                "Star Wars series":1,
                "Harry Potter series":2,
                "Love Actually":3,
                "Casablanca":4,
                "Toy Story series":5,
                "2001 Space Odyssey":6,
                "Back to the Future":7,
                "Apocalypse Now":8,
                "None of the above films":9,
                "Friends":0,
                "Only Fools and Horses":1,
                "Doctor Who":2,
                "Downtown Abbey":3,
                "Gavin and Stacey":4,
                "Game of Thrones":5,
                "The Thick of It":6,
                "The Inbetweeners":7,
                "The Next Step":8,
                "None of the above tv shows":9,
                "I mostly watch live TV (eg news or sports)":0,
                "I mostly watch recorded programs on my TV":1,
                "I mostly watch TV series online (computer, tablet, iPad, phone, etc.)":2,
                "I don't really watch TV programs":3,
                 "I don't use any social media app":0,
                "Facebook":1,
                "Twitter":2,
                "WhatsApp":3,
                "Instagram":4,
                "Pinterest":5,
                "Snapchat":6,
                "LinkedIn":7,
                "I don't own a smart phone":0,
                "Less than 5 hours":1,
                "Between 5 and 10 hours":2,
                "Between 10 and 20 hours":3,
                "Between 20 and 30 hours":4,
                "More than 30 hours":5,
                "I mostly use cash":0,
                "I mostly use cards":1,
                "I mostly use Apple Pay or Android Pay or Samsung Pay":2,
                }
                 
                 
                 